version: "3.9"

services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    container_name: dockge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dockge.rule=Host(`dockge.${BASE_DOMAIN:-ozeliurs.com}`)"
        - "traefik.http.routers.dockge.entrypoints=websecure"
        - "traefik.http.routers.dockge.tls=true"
        - "traefik.http.routers.dockge.tls.certresolver=cloudflare"
        - "traefik.http.routers.dockge.service=dockge"
        - "traefik.http.services.dockge.loadbalancer.server.port=5001"

networks:
  traefik:
    external: true